# Official doc at https://detekt.dev/docs/rules/style#libraryentitiesshouldnotbepublic

complexity:
  LargeClass:
    active: false

  LongMethod:
    active: false

  LongParameterList:
    functionThreshold: 10
    ignoreAnnotated: [ 'Composable' ]
    ignoreDefaultParameters: true

  TooManyFunctions:
    ignoreAnnotatedFunctions: [ 'Composable', 'Preview', 'PreviewLightDark' ]
    ignoreOverridden: true
    ignorePrivate: true

empty-blocks:
  EmptyFunctionBlock:
    ignoreOverridden: true

formatting:
  ArgumentListWrapping:
    maxLineLength: 150

  CommentWrapping:
    active: false

  MaximumLineLength:
    maxLineLength: 150

  PropertyWrapping:
    maxLineLength: 150

naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]

  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'

style:
  MagicNumber:
    ignoreAnnotated: [ 'Composable' ]
    ignorePropertyDeclaration: true

  MaxLineLength:
    maxLineLength: 150

  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview', 'PreviewLightDark' ]
