# Official doc at https://detekt.dev/docs/rules/style#libraryentitiesshouldnotbepublic

comments:
  AbsentOrWrongFileLicense:
    active: true

  DeprecatedBlockTag:
    active: true

  OutdatedDocumentation:
    active: true

  UndocumentedPublicClass:
    active: true

  UndocumentedPublicFunction:
    active: true

  UndocumentedPublicProperty:
    active: true

complexity:
  ComplexInterface:
    active: true

  LargeClass:
    active: false

  LongMethod:
    active: false

  LongParameterList:
    functionThreshold: 10
    ignoreAnnotated: [ 'Composable' ]
    ignoreDefaultParameters: true

  NamedArguments:
    active: true

  NestedScopeFunctions:
    active: true

  ReplaceSafeCallChainWithRun:
    active: true

  StringLiteralDuplication:
    active: true

  TooManyFunctions:
    ignoreAnnotatedFunctions: [ 'Composable', 'Preview', 'PreviewLightDark' ]
    ignoreOverridden: true
    ignorePrivate: true

coroutines:
  GlobalCoroutineUsage:
    active: true

empty-blocks:
  EmptyFunctionBlock:
    ignoreOverridden: true

formatting:
  ArgumentListWrapping:
    maxLineLength: 150

  CommentWrapping:
    active: false

  FunctionReturnTypeSpacing:
    maxLineLength: 150

  MaximumLineLength:
    maxLineLength: 150

  ParameterListWrapping:
    maxLineLength: 150

  ParameterWrapping:
    maxLineLength: 150

  PropertyWrapping:
    maxLineLength: 150

  Wrapping:
    maxLineLength: 150

naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]

  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'

potential-bugs:
  DontDowncastCollectionTypes:
    active: true

style:
  CascadingCallWrapping:
    active: true

  ClassOrdering:
    active: true

  CollapsibleIfStatements:
    active: true

  MagicNumber:
    ignoreAnnotated: [ 'Composable' ]
    ignorePropertyDeclaration: true

  MaxLineLength:
    maxLineLength: 150

  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview', 'PreviewLightDark' ]
