name: Submit dependency graph

on:
  push:
    branches:
      - main

jobs:
  submit-dependency-graph:
    name: Submit dependency graph
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      USERNAME: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Submit dependency graph
        uses: gradle/actions/dependency-submission@v3
        with:
          cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}
