name: Build & upload to Firebase App Distribution

on:
  workflow_call:
    inputs:
      isSnapshot:
        required: false
        default: false
        type: boolean
    secrets:
      KEY_PASSWORD:
        required: true
      FIREBASE_CREDENTIAL_FILE_CONTENT:
        required: true
      FIREBASE_GROUP:
        required: true
      FIREBASE_APP_ID:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DEMO_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      IS_SNAPSHOT: ${{ inputs.isSnapshot }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: assembleRelease
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIAL_FILE_CONTENT }}
          groups: ${{ secrets.FIREBASE_GROUP }}
          file: pillarbox-demo/build/outputs/apk/release/pillarbox-demo-release.apk
