# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run test on PR on Main

on:
  pull_request:
    branches:
      -main
    types: [synchronize, opened]

permissions:
  contents: read

jobs:
  tests:
    if: github.event.pull_request.draft == false
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup and execute Gradle 'buildDebug' task
      uses: gradle/gradle-build-action@v2
      with:
        arguments: buildDebug
    - name: AVD cache
      uses: actions/cache@v3
      id: avd-cache
      with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-26
    - name: create AVD and generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
          api-level: 26
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
          api-level: 26
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck
